project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Excercises
        menu: 
          - text: Hands-on Excercise (Geospatial Data Wrangling with R)
            href: Hands-on_Ex1.qmd
          - text: Hands-on Excercise (Choropleth Mapping with R)
            href: Hands-on_Ex1b.qmd
          - text: Hands-on Excercise (Global and Local Measures of Spatial Autocorrelation)
            href: Hands-on_Ex2.qmd 
          - text: Hands-on Excercise (Spatially Constrained Clustering Techniques)
            href: Hands-on_Ex3.qmd
          - text: Hands-on Excercise (Calibrating Hedonic Pricing Model with GWR Method)
            href: Hands-on_Ex4.qmd
          - text: Hands-on Excercise 5
            href: Hands-on_Ex5.qmd
            
      - text: In Class Excercises
        menu: 
          - text: In class Ex (Spatial Weights and Applications)
            href: In-class/In-class_Ex1/In-class_Ex1.qmd
          - text: In class Ex 2
            href: In-class/In-class_Ex2/In-class_Ex2.qmd
          - text: In class Ex (Spatially Constrained Clustering with ClustGeo)
            href: In-class/In-class_Ex3/In-class_Ex3.qmd
          - text: In class Ex 4 (Calibrating Hedonic Pricing Model with GWR Method, updated)
            href: In-class/In-class_Ex4/In-class_Ex4.qmd
          - text: In class Ex 5
            href: In-class/In-class_Ex5/In-class_Ex5.qmd
            
      - text: Take home Excercises
        menu: 
          - text: Take home Excercise 1
            href: Take-Home/Take-home_Ex1/Take-home_Ex1.qmd
          - text: Take home Excercise 2
            href: Take-Home/Take-home_Ex2/Take-home_Ex2.qmd
          
            
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: Journal
    
    css: styles.css
    toc: true

editor: visual

