project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Excercises
        menu: 
          - text: Hands-on Excercise 1(a)
            href: Hands-on_Ex1.qmd
          - text: Hands-on Excercise 1(b)
            href: Hands-on_Ex1b.qmd
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

