project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Excercises
        menu: 
          - text: Hands-on Excercise 1
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

